"""
=======================================================================
STREAMLIT DASHBOARD — Delhivery Network Intelligence
=======================================================================
SETUP:
    pip install streamlit plotly pandas numpy xgboost networkx

RUN:
    streamlit run streamlit_app.py

REQUIRED FILES IN SAME FOLDER (already generated by your pipeline):
    - node_metrics.csv
    - corridor_edge_table.csv
    - chronic_corridors.csv
    - delivery_data.csv          (original dataset)
    - delhivery_network.gexf     (optional, for full graph stats)

WHAT IT SHOWS:
    1. Network-wide KPI strip (live, computed from data)
    2. Bottleneck hub explorer with delay-risk score
    3. ETA predictor — pick source/destination/time, get prediction
    4. Corridor risk lookup — type any corridor, see its risk profile
=======================================================================
"""

import streamlit
import pandas
import plotly

# ─────────────────────────────────────────────────────────────────────
# PAGE CONFIG
# ─────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Delhivery Network Intelligence",
    page_icon="📦",
    layout="wide",
)

st.markdown("""
<style>
.metric-card {
    background-color: #161b22;
    border: 1px solid #30363d;
    border-radius: 8px;
    padding: 16px;
    text-align: center;
}
.metric-val { font-size: 28px; font-weight: 700; color: #FF6B6B; }
.metric-label { font-size: 12px; color: #8b949e; text-transform: uppercase; }
</style>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────
# LOAD DATA (cached)
# ─────────────────────────────────────────────────────────────────────
@st.cache_data
def load_data():
    df = pd.read_csv('delivery_data.csv')
    for col in ['od_start_time']:
        df[col] = pd.to_datetime(df[col], errors='coerce')
    df['hour_of_day'] = df['od_start_time'].dt.hour
    df['day_of_week'] = df['od_start_time'].dt.dayofweek
    df['delay_ratio'] = df['segment_actual_time'] / df['segment_osrm_time'].replace(0, np.nan)
    df['sla_breach']  = (df['segment_factor'] > 1.20).astype(int)
    df['is_ftl']      = (df['route_type'] == 'FTL').astype(int)
    df = df[(df['segment_actual_time'] > 0) & (df['segment_osrm_time'] > 0)]
    df = df.dropna(subset=['source_center','destination_center'])

    node_metrics = pd.read_csv('node_metrics.csv')
    edge_df      = pd.read_csv('corridor_edge_table.csv')
    chronic      = pd.read_csv('chronic_corridors.csv')
    return df, node_metrics, edge_df, chronic

with st.spinner("Loading network data..."):
    df, node_metrics, edge_df, chronic = load_data()

# Build name lookup for display
name_lookup = dict(zip(df['source_center'], df['source_name']))
name_lookup.update(dict(zip(df['destination_center'], df['destination_name'])))

# ─────────────────────────────────────────────────────────────────────
# HEADER + KPI STRIP
# ─────────────────────────────────────────────────────────────────────
st.title("📦 Delhivery Network Intelligence Dashboard")
st.caption("Graph-based delay risk monitoring | Live from corridor & hub metrics")

total_trips    = len(df)
breach_rate    = df['sla_breach'].mean() * 100
n_corridors    = len(edge_df)
n_chronic      = len(chronic)
n_hubs         = len(node_metrics)
avg_delay      = df['segment_factor'].mean()

c1, c2, c3, c4, c5, c6 = st.columns(6)
for col, val, label in zip(
    [c1,c2,c3,c4,c5,c6],
    [f"{total_trips:,}", f"{breach_rate:.1f}%", f"{n_corridors:,}",
     f"{n_chronic:,}", f"{n_hubs:,}", f"{avg_delay:.2f}×"],
    ["Total Trips", "SLA Breach Rate", "Corridors",
     "Chronic Corridors", "Facilities", "Avg Delay Factor"]
):
    col.markdown(f"""
    <div class="metric-card">
        <div class="metric-val">{val}</div>
        <div class="metric-label">{label}</div>
    </div>
    """, unsafe_allow_html=True)

st.divider()

# ─────────────────────────────────────────────────────────────────────
# TABS
# ─────────────────────────────────────────────────────────────────────
tab1, tab2, tab3, tab4 = st.tabs([
    "🔥 Bottleneck Hub Explorer",
    "📍 Corridor Risk Lookup",
    "⏱️ ETA Risk Estimator",
    "📊 Network Trends"
])

# ════════════════════════════════════════════════════════════════════
# TAB 1 — BOTTLENECK HUB EXPLORER
# ════════════════════════════════════════════════════════════════════
with tab1:
    st.subheader("Top Bottleneck Hubs — Live Ranking")

    n_show = st.slider("Number of hubs to show", 5, 30, 10)
    top_hubs = node_metrics.head(n_show).copy()
    top_hubs['display_name'] = top_hubs['facility_name'].fillna(top_hubs['center'])

    col_a, col_b = st.columns([1.3, 1])

    with col_a:
        fig = px.bar(
            top_hubs.sort_values('bottleneck_score'),
            x='bottleneck_score', y='display_name',
            orientation='h',
            color='sla_breach_rate',
            color_continuous_scale='Reds',
            labels={'bottleneck_score':'Bottleneck Score',
                    'display_name':'Facility',
                    'sla_breach_rate':'SLA Breach Rate'},
            title=f"Top {n_show} Bottleneck Hubs"
        )
        fig.update_layout(height=max(400, n_show*28), template='plotly_dark')
        st.plotly_chart(fig, use_container_width=True)

    with col_b:
        fig2 = px.scatter(
            top_hubs, x='betweenness', y='sla_breach_rate',
            size='total_degree', color='bottleneck_score',
            hover_name='display_name',
            color_continuous_scale='Reds',
            labels={'betweenness':'Betweenness Centrality',
                    'sla_breach_rate':'SLA Breach Rate'},
            title="Betweenness vs SLA Breach Rate"
        )
        fig2.update_layout(height=max(400, n_show*28), template='plotly_dark')
        st.plotly_chart(fig2, use_container_width=True)

    st.subheader("Hub Detail")
    selected_hub = st.selectbox(
        "Select a hub to inspect",
        options=top_hubs['center'].tolist(),
        format_func=lambda x: name_lookup.get(x, x)
    )

    hub_row = node_metrics[node_metrics['center']==selected_hub].iloc[0]
    hub_trips = df[df['source_center']==selected_hub]

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("SLA Breach Rate", f"{hub_row['sla_breach_rate']*100:.1f}%")
    m2.metric("Betweenness", f"{hub_row['betweenness']*100:.2f}%")
    m3.metric("Out-degree", f"{int(hub_row['out_degree'])}")
    m4.metric("Bottleneck Score", f"{hub_row['bottleneck_score']:.3f}")

    if len(hub_trips) > 0:
        hourly = hub_trips.groupby('hour_of_day')['sla_breach'].mean().reset_index()
        fig3 = px.line(hourly, x='hour_of_day', y='sla_breach',
                       title=f"SLA Breach Rate by Hour — {name_lookup.get(selected_hub, selected_hub)}",
                       markers=True)
        fig3.update_yaxes(tickformat='.0%')
        fig3.update_layout(template='plotly_dark', height=350)
        st.plotly_chart(fig3, use_container_width=True)

# ════════════════════════════════════════════════════════════════════
# TAB 2 — CORRIDOR RISK LOOKUP
# ════════════════════════════════════════════════════════════════════
with tab2:
    st.subheader("Corridor Risk Lookup")

    all_sources = sorted(edge_df['source_center'].unique())
    col1, col2 = st.columns(2)
    with col1:
        src = st.selectbox("Source facility",
                           options=all_sources,
                           format_func=lambda x: f"{name_lookup.get(x,x)} ({x})")
    dest_options = sorted(edge_df[edge_df['source_center']==src]['destination_center'].unique())
    with col2:
        dst = st.selectbox("Destination facility",
                           options=dest_options,
                           format_func=lambda x: f"{name_lookup.get(x,x)} ({x})")

    corridor_rows = edge_df[(edge_df['source_center']==src) & (edge_df['destination_center']==dst)]

    if len(corridor_rows) > 0:
        for _, row in corridor_rows.iterrows():
            is_chronic = row['mean_factor'] > 1.20
            risk_color = "🔴" if is_chronic else "🟢"
            st.markdown(f"### {risk_color} {row['route_type']} corridor")

            cc1, cc2, cc3, cc4 = st.columns(4)
            cc1.metric("Trip Count", f"{int(row['trip_count']):,}")
            cc2.metric("Mean Delay Factor", f"{row['mean_factor']:.2f}×")
            cc3.metric("SLA Breach Rate", f"{row['sla_breach_pct']*100:.1f}%")
            cc4.metric("Avg Distance", f"{row['avg_dist_km']:.1f} km")

            if is_chronic:
                st.warning(
                    f"⚠️ This corridor is **chronically delayed** "
                    f"(actual time exceeds OSRM estimate by {(row['mean_factor']-1)*100:.0f}%). "
                    f"Recommended: review for FTL conversion or schedule shift to Evening dispatch window."
                )
            else:
                st.success("✅ This corridor is operating within SLA tolerance.")
    else:
        st.info("No direct corridor found between these facilities in the dataset.")

    # Conversion candidates table
    st.subheader("Carting → FTL Conversion Candidates")
    st.caption("Corridors with >90% SLA breach rate and >20 trips currently assigned to Carting")

    carting_high = (
        df[df['route_type']=='Carting']
        .groupby(['source_center','destination_center'])
        .agg(trips=('trip_uuid','count'), breach_rate=('sla_breach','mean'))
        .reset_index()
    )
    candidates = carting_high[(carting_high['breach_rate']>0.90) & (carting_high['trips']>20)]
    candidates = candidates.sort_values('breach_rate', ascending=False).head(20).copy()
    candidates['source_name']      = candidates['source_center'].map(name_lookup)
    candidates['destination_name'] = candidates['destination_center'].map(name_lookup)
    candidates['breach_rate_pct']  = (candidates['breach_rate']*100).round(1)

    st.dataframe(
        candidates[['source_name','destination_name','trips','breach_rate_pct']]
        .rename(columns={'source_name':'Source','destination_name':'Destination',
                          'trips':'Trips','breach_rate_pct':'Breach Rate (%)'}),
        use_container_width=True, hide_index=True
    )

# ════════════════════════════════════════════════════════════════════
# TAB 3 — ETA RISK ESTIMATOR (rule-based using corridor history)
# ════════════════════════════════════════════════════════════════════
with tab3:
    st.subheader("ETA Risk Estimator")
    st.caption(
        "Estimates expected delivery time using corridor historical delay ratios "
        "and hub bottleneck scores — the same signals driving the graph-enhanced model."
    )

    col1, col2, col3 = st.columns(3)
    with col1:
        src2 = st.selectbox("Source", options=all_sources,
                            format_func=lambda x: f"{name_lookup.get(x,x)} ({x})",
                            key="eta_src")
    dest_opts2 = sorted(edge_df[edge_df['source_center']==src2]['destination_center'].unique())
    with col2:
        dst2 = st.selectbox("Destination", options=dest_opts2,
                            format_func=lambda x: f"{name_lookup.get(x,x)} ({x})",
                            key="eta_dst")
    with col3:
        hour_select = st.slider("Dispatch hour", 0, 23, 10)

    corridor_match = edge_df[(edge_df['source_center']==src2) & (edge_df['destination_center']==dst2)]

    if len(corridor_match) > 0:
        row = corridor_match.iloc[0]
        osrm_time = row['avg_osrm_min']

        # Time-of-day adjustment from network averages
        time_bucket = ('Night' if hour_select < 6 else
                       'Morning' if hour_select < 12 else
                       'Afternoon' if hour_select < 18 else 'Evening')
        tod_factor = df[df['hour_of_day']==hour_select]['segment_factor'].mean()
        if pd.isna(tod_factor):
            tod_factor = row['mean_factor']

        corridor_factor = row['mean_factor']
        # Blend corridor-specific and time-of-day signal
        blended_factor = 0.7 * corridor_factor + 0.3 * tod_factor
        est_time = osrm_time * blended_factor

        st.markdown(f"#### Estimated delivery time: **{est_time:.0f} minutes**")
        st.caption(f"(OSRM baseline estimate: {osrm_time:.0f} min — graph-adjusted by {blended_factor:.2f}×)")

        b1, b2, b3 = st.columns(3)
        b1.metric("OSRM Estimate", f"{osrm_time:.0f} min")
        b2.metric("Graph-Adjusted Estimate", f"{est_time:.0f} min",
                  delta=f"+{est_time-osrm_time:.0f} min")
        b3.metric("Corridor SLA Breach Rate", f"{row['sla_breach_pct']*100:.1f}%")

        if row['sla_breach_pct'] > 0.80:
            st.error(
                f"🔴 High risk corridor — {row['sla_breach_pct']*100:.0f}% of historical trips "
                f"breached SLA. Consider buffer time of +{est_time-osrm_time:.0f} min in customer commitment."
            )
        elif row['sla_breach_pct'] > 0.50:
            st.warning(f"🟡 Moderate risk corridor — {row['sla_breach_pct']*100:.0f}% historical breach rate.")
        else:
            st.success(f"🟢 Low risk corridor — {row['sla_breach_pct']*100:.0f}% historical breach rate.")

        st.caption(f"Dispatch window: {time_bucket} | Network avg delay factor for this hour: {tod_factor:.2f}×")
    else:
        st.info("No historical corridor data for this source-destination pair.")

# ════════════════════════════════════════════════════════════════════
# TAB 4 — NETWORK TRENDS
# ════════════════════════════════════════════════════════════════════
with tab4:
    st.subheader("Network-Wide Trends")

    col1, col2 = st.columns(2)

    with col1:
        hourly_all = df.groupby(['hour_of_day','route_type'])['sla_breach'].mean().reset_index()
        fig4 = px.line(hourly_all, x='hour_of_day', y='sla_breach', color='route_type',
                       title="SLA Breach Rate by Hour & Route Type", markers=True)
        fig4.update_yaxes(tickformat='.0%')
        fig4.update_layout(template='plotly_dark', height=400)
        st.plotly_chart(fig4, use_container_width=True)

    with col2:
        heat = df.pivot_table(index='hour_of_day', columns='route_type',
                              values='segment_factor', aggfunc='mean')
        fig5 = px.imshow(heat, color_continuous_scale='RdYlGn_r',
                         title="Delay Factor Heatmap (Hour × Route Type)",
                         labels=dict(color="Delay Factor"))
        fig5.update_layout(template='plotly_dark', height=400)
        st.plotly_chart(fig5, use_container_width=True)

    st.subheader("Top 10 Chronic Corridors")
    chronic_display = chronic.head(10).copy()
    chronic_display['source_name']      = chronic_display['source_center'].map(name_lookup)
    chronic_display['destination_name'] = chronic_display['destination_center'].map(name_lookup)
    chronic_display['sla_breach_pct']   = (chronic_display['sla_breach_pct']*100).round(1)
    chronic_display['mean_factor']      = chronic_display['mean_factor'].round(2)

    st.dataframe(
        chronic_display[['source_name','destination_name','route_type','trip_count',
                         'mean_factor','sla_breach_pct']]
        .rename(columns={'source_name':'Source','destination_name':'Destination',
                          'route_type':'Route Type','trip_count':'Trips',
                          'mean_factor':'Delay Factor','sla_breach_pct':'SLA Breach %'}),
        use_container_width=True, hide_index=True
    )

st.divider()
st.caption(
    "Delhivery Network Intelligence | Graph: 1,657 facilities, 2,783 corridors | "
    "Built with Streamlit + Plotly | Data source: training/test trip segments"
)
